[build.environment]
  # Tell Netlify not to scan the Next.js cache folders for secrets
  SECRETS_SCAN_OMIT_PATHS = ".next/cache/webpack/*,.netlify/.next/cache/webpack/*"

[[redirects]]
  from = "/ingest/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  host = "us-assets.i.posthog.com"
  status = 200
  force = true

[[redirects]]
  from = "/ingest/*"
  to = "https://us.i.posthog.com/:splat"
  host = "us.i.posthog.com"
  status = 200
  force = true