// app/layout.tsx
import "../styles/globals.css"; // Adjusted import path for TypeScript

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        {/* You can add meta tags or links here if needed */}
      </head>
      <body>{children}</body>
    </html>
  );
}
